version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    command: sleep infinity
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_ADMIN_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Secret5555}
      DB_NAME: project_db

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Secret5555}
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD:-Secret5555}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
